### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by leosimony** [aker-gateway/aker-freeipa-playbook#7]
Is this project being used in large numbers?
I am in desperate need of a gateway server for our Infra.

I have configured Json method aker and its working as expected. But for 500+ servers and growing and dynamic user config Infra, its not easy to modify Json files. 

I don't have any idea about FreeIPA. Read like bind packages and IPA server need DNS configs and all. We already running local dns with dnsmasq. 
Will it be an issue if we choose exeternal DNS for freeIPA.
Hosts and users management can be done in gui?

**Comment by anazmy** [comment]
I get your point and there should be a tool add/del/edit entries.

What are the features you want to see in such tool?
csv import maybe?

That being said, this issue is opened against the wrong repo - this is the repo fro the ansible playbook installer - may I ask you to open an issue [here](https://github.com/aker-gateway/Aker/issues) instead.

**Comment by leosimony** [comment]
Hello Anazmy, I have opened the thread on the other link you have mentioned. 
Thank you for your reply. I am closing this one.
